package my.projecteuler;

import static java.util.stream.Collectors.summingInt;
import static my.projecteuler.FibonacciIterator.*;

import java.util.function.Predicate;
import java.util.stream.Stream;

/**
 * <h1><a href="http://projecteuler.net/problem=2">Even Fibonacci numbers</a></h1>
 * 
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: <br>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * </p>
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * </p>
 * 
 * @author Tatiana Fesenko <tatiana.fesenko@gmail.com>
 */
public class Problem2 {
	public static void main(String[] args) {
		int maxValue = 4_000_000;
		int sum = intFibonacci(doNotExceed(maxValue)).filter(isEven()).collect(
				summingInt(v -> v));
		System.out.println("Result: " + sum);
	}

	private static Predicate<Integer> doNotExceed(int maxValue) {
		return v -> v <= maxValue;
	}

	private static Predicate<? super Integer> isEven() {
		return v -> v % 2 == 0;
	}

	private static Stream<Integer> intFibonacci(
			final Predicate<Integer> continuationCondition) {
		return toStream(new FibonacciIterator<Integer>(-1, 1, 2, (v1, v2) -> v1
				+ v2) {
			@Override
			public boolean hasNext() {
				return continuationCondition.test(calculateNext());
			}
		});
	}

}
